package commen;

import java.io.Serializable;

import ennam.ObjectType;
import ennam.OperationType;
/**
 * Command - this is a query that sends to server.<br>
 * Command is implemented as a shell that consists number of parameters
 * are showing which object requires to be sent to server.
 * @ Group 7
 *
 */
public class Com implements Serializable{

	/**
 * 
 */
private static final long serialVersionUID = -7019839106023060854L;

/** Type of object that requires to be sent to server
 * @see ObjectType */
private ObjectType type;

/**Type of operation that must be performed under sending object
 * @see OperationType*/
private OperationType operation;


/**Abstract Object is implementing to specific object by DBcontroller due to
 * its operation type
 * @see OperationType
 * @see server.controllers.DBController*/
private Object object;

/**static variable that responsible for get serial number to requestNumber
 * @see requestNumber*/
private static long cnt;


/**requestNumber - this is a variable that generated by "cnt"
 * RequestNumber - indicates who sent this Command*/
private long requestNumber;

public Com(){
	cnt++;
	this.requestNumber = cnt;
}

//getters and Setters
	public ObjectType getType() {
		return type;
	}

	public void setType(ObjectType type) {
		this.type = type;
	}

	public OperationType getOperation() {
		return operation;
	}

	public void setOperation(OperationType operation) {
		this.operation = operation;
	}

	public Object getObject() {
		return object;
	}

	public void setObject(Object object) {
		this.object = object;
	}

	public long getRequestNumber() {
		return requestNumber;
	}

	
	
}



