package commen;

import java.io.Serializable;

import ennam.UserType;
/**
 * This class is an object that was returned by server as an answer 
 * to query is implemented by class Command
 * @see common.Command
 * @ Group 7
 *
 */
public class ReturnedObject implements Serializable{
	
	private static final long serialVersionUID = 5969661897931592354L;

	/**Abstract Object is implementing to specific object by DBcontroller due to
	 * its operation type
	 * @see OperationType
	 * @see server.controllers.DBController*/
	private Object obj;
	
	/**requestNumber - this is a variable that generated by "cnt"
	 * RequestNumber - indicates who sent this Command*/
	private final long requestNumber;
	
	/**
	 * Covering class for the object you want
	 * to return from server to client
	 * @param requestNumber 
	 */
	public ReturnedObject(long requestNumber){
		this.requestNumber = requestNumber;
	}
	
	public ReturnedObject(long requestNumber, Object obj){
		this.requestNumber = requestNumber;
		this.obj = obj;
	}

	//getters and setters
	public Object getObject() {
		return obj;
	}

	public void setObject(Object obj) {
		this.obj = obj;
	}

	public long getRequestNumber() {
		return requestNumber;
	}

	
	
	
}
